[package]
name = "hash_killer"
version = "0.7.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
ctrlc = "3.2"
itoa = "1.0